nome = input('Qual seu nome: ')
Mae = input('Nome da mae: ')
Pai = input('Nome do pai: ')
Rg = input('RG: ')
Cpf = input('Cpf: ')
Rua = input('Rua: ')
Numero = input('N°:')
Bairro = input('Bairo:')
Cidade = input('Cidade:')
Cep = input('Cep:')
Trabalha = input('Esta empregando: ')
nomeDoTrabalho = input('Onde Trabalha: ')

nascimento = input('Data de nascimento: ')

print('\nÉ um prazer te conhecer, {}!'.format(nome))
print('Você é filho de {} e {} '.format(Mae, Pai))
print('Seus documentos sao RG: {} e CPF: {}'.format(Rg, Cpf))
print('Seu endereço é Rua: {} Numero: {} Bairro: {} Cidade: {} Cep: {}'.format(Rua, Numero, Bairro, Cidade, Cep))
print('Empregado : {} Trabalha na  empresa: {}'.format(Trabalha, nomeDoTrabalho))